FROM node:16-alpine
WORKDIR '/app'
COPY package.json .
RUN mkdir -p node_modules/.cache
RUN chown -R node:node node_modules

RUN npm install

COPY . .

#RUN chown -R node:node node_modules

CMD ["npm", "run", "start"]
